name: Desafio 1 - Docker

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Nome da imagem Docker para testar'
        required: true
        default: alpine:latest
        type: string

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Fazer pull da imagem Docker
        run: docker pull ${{ inputs.image_name }}

      - name: Verificar imagem baixada
        run: docker image ls

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: ${{ inputs.image_name }}
