name: Desafio 1 - Docker

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Nome da imagem Docker para testar'
        required: true
        type: string

jobs:
  docker-scout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fazer pull da imagem Docker
        run: docker pull ${{ inputs.image_name }}

      - name: Verificar imagem baixada
        run: docker image ls

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare
          image: image://${{ inputs.image_name }}
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}

