name: Desaio 1 - Docker


on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Nome da imagem Docker para testar'
        required: true
        default: alpine:latest
        type: string

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versão do Ubuntu
        run: cat /etc/os-release

      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de Github Actions da Linuxtips"

      - name: Fazer pull da imagem Docker
        run: docker pull ${{ inputs.image_name }}

      - name: Listar imagens Docker
        run: docker image ls

      - name: Analisar imagem com Docker Scout
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: ${{ inputs.image_name }}
