name: Vendo arquivo compartilhados entre jobs

on:
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
        - name: Confere versão do Ubuntu
          run: cat /etc/os-release

        - name: Exibir uma mensagem
          run: echo "Estou fazendo o curso de Github Actions da Linuxtips" > ${{ github.workspace }}/mensagem.txt

        - uses: actions/upload-artifact@v4
          with:
            name: strigus-upload
            path: ${{ github.workspace }}/mensagem.txt
          
  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
        - name: Listar o diretorio
          run: ls -lha

        - uses: actions/download-artifact@v4
          with:
            name: strigus-upload
            path: strigus
        
        - name: Listar o diretorio
          run: ls -lha && ls ./strigus/

        - name: Acessa o arquivo
          run: mv strigus/mensagem.txt . && rm -rf ./strigus

        - name: Listar o diretorio
          run: ls -lha
        - name: Exibir o conteúdo do arquivo
          run: cat mensagem.txt